#!/usr/bin/bash

yes | sudo apt-get update
yes | sudo apt-get install wget curl make gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf python3 git

yes | sudo dpkg --add-architecture armhf
yes | sudo apt-get update

yes | sudo apt-get install libssl-dev:armhf zlib1g-dev:armhf

git clone https://github.com/thewh1teagle/python3.8-arm-static-cross-compile.git

cd python3.8-arm-static-cross-compile
chmod +x python3.8-arm-static-compile

./python3.8-arm-static-compile
