#!/usr/bin/bash

sudo apt-get update
sudo apt-get install wget curl make gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf python3 git

sudo dpkg --add-architecture armhf
sudo apt-get update

sudo apt-get install libssl-dev:armhf zlib1g-dev:armhf

git clone https://github.com/thewh1teagle/python3.8-arm-static-cross-compile.git

cd python3.8-arm-static-cross-compile
chmod +x python3.8-arm-static-compile

./python3.8-arm-static-compile
