#!/usr/bin/bash

check_status() { # Params: ERROR , HANDLER
  STATUS_CODE=$?

  RED='\033[0;31m'
  NC='\033[0m' # No Color
  if [ $STATUS_CODE -ne 0 ]; then
      echo -e "${RED}${1}${NC}"
      ($2)
  fi
}

clean_handler() {
  read -p "do you want to clean all the stuff we installed?  (y/n)?" CONT
  if [ "$CONT" = "y" ]; then
    yes | sudo apt-get autoremove libssl-dev:armhf zlib1g-dev:armhf >/dev/null 2>&1
    yes | sudo dpkg --remove-architecture armhf > /dev/null 2>&1
  fi
  trap "exit 1" TERM
  export TOP_PID=$$
  kill -s TERM $TOP_PID
}



requirements="wget curl make gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf python3 git"
yes | sudo apt-get update
yes | sudo apt-get install "$requirements"
sudo dpkg --add-architecture armhf && yes | sudo apt-get update
yes | sudo apt-get install libssl-dev:armhf zlib1g-dev:armhf

check_status "ERROR installing dependinces" clean_handler


git clone https://github.com/thewh1teagle/python3.8-arm-static-cross-compile.git
check_status "couldn't clone the repo" clean_handler

repo="python3.8-arm-static-cross-compile"
cd "$repo" && chmod +x "$repo"
./"$repo"

clean_handler




